#!/bin/bash -eu
set -x
set -o pipefail
PATH="/usr/sbin:/usr/bin:/sbin:/bin"
cleanup_dirs=()
cleanup_devs=()
declare -A flavors=(
    ["desktop"]='http://releases.ubuntu.com/18.04/ubuntu-18.04.1-desktop-amd64.iso'
    ["live-server"]='http://releases.ubuntu.com/18.04/ubuntu-18.04.1.0-live-server-amd64.iso'
    ["server"]='http://cdimage.ubuntu.com/releases/18.04.1/release/ubuntu-18.04.1-server-amd64.iso'
)
zero="$(readlink -f "$0")"
zero_dir="${zero%/*}"
exec 3>&1
USBInstaller() {
    local block_device="$1" flavor="${2:-ubuntu-18.04.1-desktop}" mountpoint ubuntu_file
    local flavor_url="${flavors[$flavor]}"
    echo "Installing $flavor_url to $block_device"
    cleanup_devs+=("$block_device")
    ubuntu_file=$(FetchISO "$flavor_url")
    echo "ISO file: $ubuntu_file"
    UnmountBlockDeviceFilesystems "$block_device"
    mountpoint=$(MakeBootableBlockDevice "$block_device")
    cleanup_dirs+=("$mountpoint")
    DumpUbuntuOntoDevice "$mountpoint" "$ubuntu_file"
    echo "Syncing"
    sync
    exit 0
}

FetchISO() {
    local url="$1" sha_url="${1%/*}/SHA256SUMS" file="${1##*/}" sha_file="$zero_dir/SHA256SUMS"
    local full_file="$zero_dir/$file"
    curl --location --silent --show-error "$sha_url" | fgrep "$file" > "$sha_file"
    if ! (cd "$zero_dir"; sha256sum --quiet --check "$sha_file" 1>&3 ); then
	rm -vf "$full_file" 1>&3
	curl --location --fail --output "$full_file" "$url" 1>&3
	(cd "$zero_dir"; sha256sum --quiet --check "$sha_file") 1>&3
    fi
    echo "$full_file"
}

UnmountBlockDeviceFilesystems() {
    local block_device="$1" mountpoint
    lsblk --noheadings --output MOUNTPOINT "$block_device" |
	while read -r mountpoint; do
	    if [ -n "$mountpoint" ]; then
		umount -f "$mountpoint"
	    fi
	done
}

MakeBootableBlockDevice() {
    local block_device="$1" block_device_partition="${1}1" wait
    parted -a optimal "$block_device" mklabel msdos 1>&3
    parted -a optimal "$block_device" -- mkpart primary fat32 1M -1M 1>&3
    for wait in 1 2 3 4 5; do
	[ -r "$block_device_partition" ] && break
	: echo "$wait"
	sleep 1
    done
    mkfs.fat -F 32 "$block_device_partition" 1>&3
    local uuid
    uuid=$(lsblk --noheadings --output UUID "$block_device_partition")
    local mountpoint="/media/$uuid"
    mkdir -p "$mountpoint"
    mount "$block_device_partition" "$mountpoint"
    local boot="$mountpoint/boot" efi="$mountpoint/EFI"
    mkdir -p "$mountpoint/EFI"
    grub-install --no-floppy --boot-directory="$boot" --target=i386-pc "$block_device"
    grub-install --removable --boot-directory="$boot" --efi-directory="$efi" --target=x86_64-efi "$block_device"
    grub-install --removable --boot-directory="$boot" --efi-directory="$efi" --target=i386-efi "$block_device"
    echo "$mountpoint"
}

DumpUbuntuOntoDevice() {
    local mountpoint="$1" ubuntu_file="$2"
    7z x -o"$mountpoint" -aoa "$ubuntu_file"
}


Cleanup() {
    set +e -x
    local dev dir
    for dev in "${cleanup_devs[@]}"; do
	UnmountBlockDeviceFilesystems "$dev"
    done

    for dir in "${cleanup_dirs[@]}"; do
	rmdir "$dir"
    done
}

trap "Cleanup" EXIT
trap 'kill -INT $$' INT
trap 'kill -TERM $$' TERM
trap 'kill -QUIT $$' QUIT
USBInstaller "$@"
